investment_risk_analysis:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      database: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_NAME') }}"
      port: {{ env_var('DB_PORT') }}