version: 2

models: # <--- Should have NO indentation
  - name: dim_date
    config:
      contract:
        enforced: true
    columns:
      - name: date_id
        data_type: bigint
        constraints:
          - type: primary_key
        description: "Unique surrogate key for the date dimension"
      - name: trade_date
        data_type: date
      - name: year
        data_type: int
      - name: quarter
        data_type: tinyint # Using tinyint for efficiency
      - name: month
        data_type: tinyint
      - name: day
        data_type: tinyint
      - name: weekday
        data_type: tinyint

  - name: dim_symbol
    config:
      contract:
        enforced: true
    columns:
      - name: symbol_id
        data_type: bigint
        constraints:
          - type: primary_key
        description: "Unique surrogate key for the symbol dimension"
      - name: symbol
        data_type: varchar(255)
      - name: security
        data_type: text
      - name: gics_sector
        data_type: text
      - name: gics_industry
        data_type: text

  - name: fact_price
    config:
      contract:
        enforced: true
    columns:
      - name: symbol_id
        data_type: bigint
        constraints:
          - type: foreign_key
            to: ref('dim_symbol')
            field: symbol_id
      - name: date_id
        data_type: bigint
        constraints:
          - type: foreign_key
            to: ref('dim_date')
            field: date_id
      - name: open_price
        data_type: decimal(10,2)
      - name: high_price
        data_type: decimal(10,2)
      - name: low_price
        data_type: decimal(10,2)
      - name: close_price
        data_type: decimal(10,2)
      - name: volume
        data_type: bigint