name: dbt Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-mysql
    - name: Run dbt
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        cd dbt
        dbt deps
        dbt run